language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - hhvm

branches:
    only:
        - master
        - develop

before_script:
    - wget http://getcomposer.org/composer.phar
    - php composer.phar dump-autoload
